language: php

dist: trusty

php:
  - 7.1.18
  - 7.2
  - 7.3

sudo: false

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
